package com.armen.osipyan.http;

public enum Endpoint {
    POST_CREATE_OR_UPDATE_TASK,
    POST_CREATE_OR_UPDATE_EPIC,
    POST_CREATE_OR_UPDATE_SUB_TASK,
    DELETE_EPIC,
    DELETE_TASK,
    DELETE_SUBTASK,
    DELETE_ALL_TASK,
    DELETE_ALL_EPIC,

    DELETE_ALL_SUB_TASK,
    GET_ALL_TASK,
    GET_ALL_EPIC,
    GET_ALL_SUB_TASK,
    GET_SUB_TASK_FROM_EPIC,

    GET_EPIC,
    GET_TASK,
    GET_SUB_TASK,
    GET_HISTORY,
    GET_PRIORITIZED_TASK,
    UNKNOWN
}
